# Generated by Django 5.0.7 on 2025-06-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaignid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donorid', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Treasurer',
            fields=[
                ('treasurerid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donationid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_donated', models.DateTimeField(auto_now_add=True)),
                ('campaignid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SadaqahEase.campaign')),
                ('donorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SadaqahEase.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('total_donations', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SadaqahEase.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('financialid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('source', models.CharField(blank=True, choices=[('Online Donation', 'Online Donation'), ('Tabung (Physical Box)', 'Tabung (Physical Box)'), ('Campaign', 'Campaign'), ('Others', 'Others')], max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('Asnaf Support', 'Asnaf Support'), ('Mosque Maintenance', 'Mosque Maintenance'), ('Utilities', 'Utilities'), ('Education Program', 'Education Program'), ('Community Event', 'Community Event'), ('Others', 'Others')], max_length=50, null=True)),
                ('description', models.TextField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SadaqahEase.treasurer')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=20)),
                ('date_received', models.DateField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SadaqahEase.treasurer')),
            ],
        ),
    ]
