# Generated by Django 5.0.7 on 2025-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaignimage',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
    ]
