# Generated by Django 5.0.7 on 2025-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0002_campaign_campaignimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='donation_receipts/'),
        ),
    ]
