# Generated by Django 5.0.7 on 2025-06-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0003_donation_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('General', 'General Donation'), ('Campaign', 'Campaign Donation')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date_donated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationid',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
