# Generated by Django 5.0.7 on 2025-06-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0004_donation_donation_type_alter_donation_date_donated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabungDonation',
            fields=[
                ('donationid', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
