# Generated by Django 5.0.7 on 2025-06-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0006_alter_campaign_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateFund',
            fields=[
                ('allocateid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Education Program', 'Education Program'), ('Mosque Maintenance', 'Mosque Maintenance'), ('Asnaf Support', 'Asnaf Support'), ('Utilities', 'Utilities'), ('Community Event', 'Community Event'), ('Others', 'Others')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=200)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SadaqahEase.treasurer')),
            ],
        ),
    ]
