# Generated by Django 5.0.7 on 2025-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0008_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='hidden_from_donor',
            field=models.BooleanField(default=False),
        ),
    ]
