# Generated by Django 5.0.7 on 2025-06-27 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0009_donation_hidden_from_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
