# Generated by Django 5.0.7 on 2025-06-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0010_donor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SadaqahEase.campaign'),
        ),
    ]
