# Generated by Django 5.0.7 on 2025-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0011_financial_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default='reports/placeholder.pdf', upload_to='reports/'),
            preserve_default=False,
        ),
    ]
