# Generated by Django 5.0.7 on 2025-07-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SadaqahEase', '0012_report_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationRecord',
        ),
    ]
